<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProductTwoEdit extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string|max:255',
            'description' => 'required',
            'price' => 'required',
            'offer' => 'required',
            'qty' => 'required',
            'image' => 'nullable|image',
            'category_id' => 'required|exists:categories,id',
            'colors' => 'required|array',
            'colors.*' => 'required|string|min:1',
            'sizes' => 'required|array',
            'sizes.*' => 'required|string|min:1',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
